Update sample pipeline, reduce deploy to just docker compose + compose build (no independent image build).

diff --git a/deploy/assets/out b/deploy/assets/out
--- a/deploy/assets/out
+++ b/deploy/assets/out
@@ -11,37 +11,32 @@ cd "$1"
 jq -M . < /dev/stdin | tee /tmp/stdin.json &> /dev/null
 
 JSON_OUT='{ "version": {}, "metadata": [] }'
-DEBUG=$(jq ".source.debug" -r /tmp/stdin.json)
-APPKU_HOST=$(jq ".source.host // \"localhost\"" -r /tmp/stdin.json)
-APPKU_USERNAME=$(jq ".source.sa.username // \"appku\"" -r /tmp/stdin.json)
-APPKU_PASSWORD=$(jq ".source.sa.password // \"\"" -r /tmp/stdin.json)
-SOURCE=$(jq ".params.source" -r /tmp/stdin.json)
-MODE=$(jq ".params.mode // \"compose\"" -r /tmp/stdin.json)
-if [[ "$MODE" != "image" && "$MODE" != "compose" ]]; then
-    echo -e "\033[0;31mInvalid parameter 'mode'. Expected either 'compose' or 'image'.\033[0m"
+SOURCE_DEBUG=$(jq ".source.debug" -r /tmp/stdin.json)
+SOURCE_HOST=$(jq ".source.host // \"localhost\"" -r /tmp/stdin.json)
+SOURCE_APPS_REGISTRY_HOST=$(jq ".source.apps.registry // \"registry.$SOURCE_HOST\"" -r /tmp/stdin.json)
+SOURCE_APPS_JIDO_HOST=$(jq ".source.apps.jido // \"jido.$SOURCE_HOST\"" -r /tmp/stdin.json)
+SOURCE_APPS_USERNAME=$(jq ".source.apps.username // \"appku\"" -r /tmp/stdin.json)
+SOURCE_APPS_PASSWORD=$(jq ".source.apps.password // \"\"" -r /tmp/stdin.json)
+PARAMS_SOURCE=$(jq ".params.source" -r /tmp/stdin.json)
+PARAMS_COMPOSE_FILE=$(jq ".params.compose.file // \"docker-compose.yml\"" -r /tmp/stdin.json)
+PARAMS_COMPOSE_TAG=$(jq ".params.compose.tag // \"\"" -r /tmp/stdin.json)
+PARAMS_COMPOSE_TAG_FILE=$(jq ".params.compose.tag_file // \"\"" -r /tmp/stdin.json)
+PARAMS_COMPOSE_TIMEOUT=$(jq ".params.compose.timeout // 15" -r /tmp/stdin.json)
+PARAMS_COMPOSE_NUKE_ORPHANS=$(jq ".params.compose.nuke_orphans // true" -r /tmp/stdin.json)
+PARAMS_COMPOSE_RECREATE=$(jq ".params.compose.recreate // true" -r /tmp/stdin.json)
+PARAMS_COMPOSE_ENV="$(jq ".params.compose.env // \"\"" -r /tmp/stdin.json)"
+if [[ -z "$PARAMS_SOURCE" ]]; then
+    echo -e "\033[0;31mThe 'source' step parameter must be set.\033[0m"
     exit 1
 fi
-PARAM_ENV="$(jq ".params.env // \"\"" -r /tmp/stdin.json)"
-if [[ -n "$PARAM_ENV" ]]; then
-    PARAM_ENV=($(</tmp/stdin.json jq -r ".params.env | keys | @tsv | gsub(\"\\t\";\" \")"))
+if [[ -n "$PARAMS_COMPOSE_TAG" && -n "$PARAMS_COMPOSE_TAG_FILE" ]]; then
+    echo -e "\033[0;31mOnly the 'tag' or 'tag_file' step parameter must be set, using both is not allowed.\033[0m"
+    exit 1
 fi
-if [[ "$MODE" == "image" ]]; then
-    if [[ -z "$(jq ".params.image.path // \"\"" -r /tmp/stdin.json)" ]]; then
-        echo -e "\033[0;31mMissing parameter 'image.path'. Expected a docker image path value.\033[0m"
-        exit 1;
-    fi
-    if [[ -z "$(jq ".params.image.tags // \"\"" -r /tmp/stdin.json)" ]]; then
-        IMAGE_TAGS=("latest")
-    else
-        IMAGE_TAGS=($(</tmp/stdin.json jq -r ".params.image.tags | @tsv | gsub(\"\\t\";\" \")"))
-    fi
-    IMAGE_PATH=$(jq ".params.image.path" -r /tmp/stdin.json)
-    REGISTRY_HOST=$(jq ".params.image.host // \"registry.$APPKU_HOST\"" -r /tmp/stdin.json)
-else
-    COMPOSE_FILE=$(jq ".params.compose.file // \"docker-compose.yml\"" -r /tmp/stdin.json)
-    COMPOSE_TIMEOUT=$(jq ".params.compose.timeout // 15" -r /tmp/stdin.json)
+if [[ -n "$PARAMS_COMPOSE_ENV" ]]; then
+    PARAMS_COMPOSE_ENV_KEYS=($(</tmp/stdin.json jq -r ".params.compose.env | keys | @tsv | gsub(\"\\t\";\" \")"))
 fi
-if [[ "$DEBUG" == 'true' ]]; then
+if [[ "$SOURCE_DEBUG" == 'true' ]]; then
     echo "Debug mode enabled."
     # printf "OUT Pipeline JSON:\n$(cat /tmp/stdin.json)\n"
     echo "## Job"
@@ -55,35 +50,35 @@ if [[ "$DEBUG" == 'true' ]]; then
     echo "BUILD_NAME = $BUILD_NAME"
     echo
     echo "## Source"
-    echo "APPKU_HOST = $APPKU_HOST"
-    echo "APPKU_USERNAME = $APPKU_USERNAME"
-    if [[ -n "$APPKU_PASSWORD" ]]; then
-        echo "APPKU_PASSWORD = *********"
+    echo "SOURCE_DEBUG = $SOURCE_DEBUG"
+    echo "SOURCE_HOST = $SOURCE_HOST"
+    echo "SOURCE_APPS_REGISTRY_HOST = $SOURCE_APPS_REGISTRY_HOST"
+    echo "SOURCE_APPS_JIDO_HOST = $SOURCE_APPS_JIDO_HOST"
+    echo "SOURCE_APPS_USERNAME = $SOURCE_APPS_USERNAME"
+    if [[ -n "$SOURCE_APPS_PASSWORD" ]]; then
+        echo "SOURCE_APPS_PASSWORD = *********"
     else
-        echo "APPKU_PASSWORD = {NOT SET}"
+        echo "SOURCE_APPS_PASSWORD = {NOT SET}"
     fi
     echo
     echo "## Parameters"
-    echo "SOURCE = $SOURCE"
-    echo "MODE = $MODE"
-    if [[ "$MODE" == "image" ]]; then
-        echo "IMAGE_PATH = $IMAGE_PATH"
-        echo "IMAGE_TAGS = $IMAGE_TAGS"
-    else
-        echo "COMPOSE_FILE = $COMPOSE_FILE"
-        echo "COMPOSE_TIMEOUT = $COMPOSE_TIMEOUT"
-    fi
-    echo
-    echo "## Custom Env"
-    if [[ -n "$PARAM_ENV" ]]; then
-        for i in "${PARAM_ENV[@]}"
+    echo "PARAMS_SOURCE = $PARAMS_SOURCE"
+    echo "PARAMS_COMPOSE_FILE = $PARAMS_COMPOSE_FILE"
+    echo "PARAMS_COMPOSE_TAG = $PARAMS_COMPOSE_TAG"
+    echo "PARAMS_COMPOSE_TAG_FILE = $PARAMS_COMPOSE_TAG_FILE"
+    echo "PARAMS_COMPOSE_TIMEOUT = $PARAMS_COMPOSE_TIMEOUT"
+    echo "PARAMS_COMPOSE_NUKE_ORPHANS = $PARAMS_COMPOSE_NUKE_ORPHANS"
+    echo "PARAMS_COMPOSE_RECREATE = $PARAMS_COMPOSE_RECREATE"
+    if [[ -n "$PARAMS_COMPOSE_ENV" ]]; then
+        echo "PARAMS_COMPOSE_ENV = {SET}"
+        for i in "${PARAMS_COMPOSE_ENV_KEYS[@]}"
         do
-            if [[ "$i" != "HOME" && "$i" != "PATH" && "$i" != "PWD" && "$i" != "SHLVL" && "$i" != "DOCKER_HOST" && "$i" != "HOSTNAME" ]]; then
-                echo "$i: $(jq ".params.env.$i // \"\"" -r /tmp/stdin.json)"
-            else
-                echo "Env '$i' ignored."
+            if [[ -n "$i" && "$i" != "HOME" && "$i" != "PATH" && "$i" != "PWD" && "$i" != "SHLVL" && "$i" != "DOCKER_HOST" ]]; then
+                echo " ➔ $i"
             fi
         done
+    else
+        echo "PARAMS_COMPOSE_ENV = {NOT SET}"
     fi
     echo
     echo "## Versions"
@@ -96,71 +91,64 @@ if [[ "$DEBUG" == 'true' ]]; then
     tree -I 'node_modules|coverage|Log|log|Docs|docs|Obj|obj'
 fi
 
-# set custom environment
-if [[ -n "$PARAM_ENV" ]]; then
-    for i in "${PARAM_ENV[@]}"
-    do
-        if [[ "$i" != "HOME" && "$i" != "PATH" && "$i" != "PWD" && "$i" != "SHLVL" && "$i" != "DOCKER_HOST" && "$i" != "HOSTNAME" ]]; then
-            PARAM_ENV_VALUE="$(jq ".params.env.$i // \"\"" -r /tmp/stdin.json)"
-            export "$i"="$PARAM_ENV_VALUE"
-            echo "exported \"$i\"=\"$PARAM_ENV_VALUE\"" >> appku.log
-        fi
-    done
-fi
-
 # ssh prep
 echo "Adding service account ssh key."
-jq ".source.sa.key" -r /tmp/stdin.json > ~/.ssh/id_rsa
+jq ".source.apps.key" -r /tmp/stdin.json > ~/.ssh/id_rsa
 echo "Adding AppKu™ host as known-host."
-ssh-keyscan -H "$APPKU_HOST" &> /dev/null > ~/.ssh/known_hosts
+ssh-keyscan -H "$SOURCE_HOST" &> /dev/null > ~/.ssh/known_hosts
 echo "Ensuring permissions."
 chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
 
 # connect to remote docker system
 echo "Creating docker context."
-docker context create appku --docker "host=ssh://$APPKU_USERNAME@$APPKU_HOST" &>> appku.log
+docker context create appku --docker "host=ssh://$SOURCE_APPS_USERNAME@$SOURCE_HOST" &>> appku.log
 echo "Switching to docker context."
 docker context use appku &>> appku.log
-JSON_OUT=$(echo "$JSON_OUT" | jq ".metadata |= .+ [{ \"name\": \"AppKu™ Host\", \"value\": \"$APPKU_HOST\" }]")
+JSON_OUT=$(echo "$JSON_OUT" | jq ".metadata |= .+ [{ \"name\": \"AppKu™ Host\", \"value\": \"$SOURCE_HOST\" }]")
 
-if [[ "$MODE" == "image" ]]; then
-    echo "Running docker image build and push from source '$(realpath $SOURCE)'."
-    cd "$(realpath $SOURCE)"
-    DOCKER_BUILD_ARGS=()
-    for i in "${IMAGE_TAGS[@]}"
-    do
-        DOCKER_BUILD_ARGS+=(-t "$IMAGE_PATH:$i")
-    done
-    docker build . "${DOCKER_BUILD_ARGS[@]}" > /tmp/docker_build_output
-    DOCKER_BUILD_DIGEST=$(cat /tmp/docker_build_output | rg '^Successfully built (.+)' -r '$1' | head -1)
-    JSON_OUT=$(echo "$JSON_OUT" | jq ".version.ref = \"$DOCKER_BUILD_DIGEST\"")
-    JSON_OUT=$(echo "$JSON_OUT" | jq ".metadata |= .+ [{ \"name\": \"AppKu™ Image Build & Deploy\", \"value\": \"$IMAGE_PATH\" }]")
-    echo "Performing docker login."
-    echo "$APPKU_PASSWORD" | docker login -u "$APPKU_USERNAME" --password-stdin "$REGISTRY_HOST"
-    echo "Performing docker push."
-    docker push -a "$IMAGE_PATH"
-    echo "Retrieving metadata"
-    for i in "${IMAGE_TAGS[@]}"
-    do
-        TAG_DIGEST="$(docker image inspect "$IMAGE_PATH:$i" -f '{{index .RepoDigests 0}}' | rg "^.+@(.+)" -r '$1')"
-        JSON_OUT=$(echo "$JSON_OUT" | jq ".metadata |= .+ [{ \"name\": \"Tag & Digest\", \"value\": \"$i, $TAG_DIGEST\" }]")
-    done
-else
-    # docker compose deploy
-    echo "Running docker compose deployment from source '$(realpath $SOURCE)'."
-    cd "$(realpath $SOURCE)"
-    # extra validation
-    COMPOSE_PROJECT=$(yq ".name // \"\"" "$COMPOSE_FILE")
-    if [[ -z "$COMPOSE_PROJECT" ]]; then
-        echo -e "\033[0;31mDocker compose file '$COMPOSE_FILE' is missing the 'name' value, which is required by AppKu™.\033[0m"
-        exit 1
+# docker compose deploy
+echo "Running docker compose deployment from source '$(realpath $PARAMS_SOURCE)'."
+cd "$(realpath $PARAMS_SOURCE)"
+if [[ -n "$PARAMS_COMPOSE_TAG_FILE" ]]; then
+    TEMP_PARAMS_COMPOSE_TAG=$(cat "$PARAMS_COMPOSE_TAG_FILE")
+    if [[ -n "$TEMP_PARAMS_COMPOSE_TAG" ]]; then
+        PARAMS_COMPOSE_TAG="$TEMP_PARAMS_COMPOSE_TAG"
     fi
-    #deploy compose file
-    docker compose -f "$COMPOSE_FILE" up --remove-orphans --force-recreate -d -t $COMPOSE_TIMEOUT
-    JSON_OUT=$(echo "$JSON_OUT" | jq ".version.ref = \"$COMPOSE_PROJECT\"")
-    JSON_OUT=$(echo "$JSON_OUT" | jq ".metadata |= .+ [{ \"name\": \"AppKu™ Compose Deploy\", \"value\": \"$COMPOSE_PROJECT\" }]")
 fi
+# extra validation
+COMPOSE_PROJECT=$(yq ".name // \"\"" "$PARAMS_COMPOSE_FILE")
+if [[ -z "$COMPOSE_PROJECT" ]]; then
+    echo -e "\033[0;31mDocker compose file '$PARAMS_COMPOSE_FILE' is missing the 'name' value, which is required by AppKu™.\033[0m"
+    exit 1
+fi
+#deploy compose file
+touch /tmp/compose.env
+if [[ -n "$PARAMS_COMPOSE_TAG" ]]; then
+    echo "TAG=$PARAMS_COMPOSE_TAG" >> /tmp/compose.env
+    echo "IMAGE_TAG=$PARAMS_COMPOSE_TAG" >> /tmp/compose.env
+fi
+if [[ -n "$PARAMS_COMPOSE_ENV" ]]; then
+    for i in "${PARAMS_COMPOSE_ENV_KEYS[@]}"
+    do
+        if [[ -n "$i" && "$i" != "HOME" && "$i" != "PATH" && "$i" != "PWD" && "$i" != "SHLVL" && "$i" != "DOCKER_HOST" ]]; then
+            #capture the env value and escape "$" with "$$" for docker
+            PARAMS_COMPOSE_ENV_VALUE="$(jq ".params.compose.env.$i // \"\"" -r /tmp/stdin.json | sed -r 's/\$/\$\$/g')"
+            echo "$i: $PARAMS_COMPOSE_ENV_VALUE" >> /tmp/compose.env
+            echo "Added env to /tmp/compose.env: \"$i\"=\"$PARAMS_COMPOSE_ENV_VALUE\"" >> appku.log
+        fi
+    done
+fi
+COMPOSE_ARGS=()
+if [[ "$PARAMS_COMPOSE_NUKE_ORPHANS" == "true" ]]; then
+    COMPOSE_ARGS+=(--remove-orphans)
+fi
+if [[ "$PARAMS_COMPOSE_RECREATE" == "true" ]]; then
+    COMPOSE_ARGS+=(--force-recreate)
+fi
+docker compose --env-file /tmp/compose.env -f "$PARAMS_COMPOSE_FILE" up "${COMPOSE_ARGS[@]}" -d -t $PARAMS_COMPOSE_TIMEOUT
+JSON_OUT=$(echo "$JSON_OUT" | jq ".version.ref = \"$COMPOSE_PROJECT\"")
+JSON_OUT=$(echo "$JSON_OUT" | jq ".metadata |= .+ [{ \"name\": \"AppKu™ Compose Deploy\", \"value\": \"$COMPOSE_PROJECT\" }]")
 
 # job return
-
+echo "Done."
 echo "$JSON_OUT" >&3
